### ISSUE TITLE
Allow users to edit a project

### ISSUE THREAD

**Issue by celinehuang** [hack4impact-mcgill/mu-crm-tool#10]
Edit a project with the PUT endpoint

Flask documentation on [Flask Blueprints](https://flask.palletsprojects.com/en/1.1.x/blueprints/#blueprints)
An example of the REST endpoints - [https://github.com/celinehuang/kom_get_your_bucha/blob/master/backend/app/items/views.py]()

**Comment by CurtisMIT** [comment]
Hey @celinehuang , 
was wondering whether we would want to enforce users to change at least one field in order to be considered an update request? As in not allowing any requests to update a project, if that request does not change any attributes of the specified project.
I see that you've implemented said behaviour in the example you provided, just wanted to confirm.

Reference:
https://github.com/celinehuang/kom_get_your_bucha/blob/master/backend/app/items/views.py#L174

**Comment by celinehuang** [comment]
@CurtisMIT Yes I think limiting the overhead for requests is always a good practice (even though we won't have too much traffic)
